###############################################################################
## snakemake config - damid pipeline ##########################################
###############################################################################
## Tom van Schaik
## 171120
## version 1.3

# Introduction snakemake:
# Snakemake is a bioinformatics pipeline tool written in python. It follows the 
# 'make'-logic: you determine rules with which files can be generated, and 
# which input files these require. Snakemake will try to execute the first rule
# given, and execute other rules based on the input the final rule requires. 
# In this way, you have a pipeline. 
# Some cool features of snakemake:
# - You give input and output file names, and snakemake will do the rest.
# - If a rule gives an error, the output file is automatically removed, to 
#   prevent "partial" data files.
# - Given a number of cores to snakemake, it will automatically parallelize 
#   things when possible. 
# - You can create a fancy workflow overview picture.

# This is the config file for a damid snakemake pipeline, where you list 
# parameters which will be used in the pipeline.

# Versions:
# 1.0 - Initial version
# 1.1 - Updated pipeline
# 1.2 - Added replicates + changed basename scheme
# 1.3 - Changed mapping to bwa mem for 4DN compatibility

###############################################################################
### Parameters and file locations #############################################
###############################################################################

# FastQC
conda_fastqc: ../../bin/fastqc/conda_fastqc.yaml

# Parsing
read_parser: bin/read_parser/read_parser.py
read_structure: bin/read_parser/read_structure_directligation.txt
conda_parser: ../../bin/read_parser/conda_parser.yaml

# Mapping
mapper: bin/mapping/mapping_bwa.sh
genome_index: /DATA/scratch/usr/t.v.schaik/data/genomes/mm10/ENCODE/mm10_no_alt_analysis_set_ENCODE
conda_mapping: ../../bin/mapping/conda_mapping.yaml

# Counting
gatc_counting: bin/gatc_counting/gatc_counting_mm10.R
gatc_gff: /DATA/scratch/usr/t.v.schaik/data/genomes/mm10/ENCODE/mm10_no_alt_analysis_set_ENCODE_gatc_fragments.gff
#bins: "5,10,20,25,50,100"
bins: "1,5"

# Normalizing
normalize_damid: bin/normalization/normalize_damid.R
normalize_method: dam-log2
pseudo: 1
combine_replicates: bin/normalization/combine_replicates.R

# Tracks
bed2bigwig: bin/data_tracks/bed2BigWig.R
chrom_sizes: /DATA/scratch/usr/t.v.schaik/data/genomes/mm10/mm10.chrom.sizes

# HMM
hmm_calling: "bin/HMM_calling/HMM.R"

# File report - the locations should be relative from the snakemake file
report_relative_location: "./"    # required for previous versions of snakemake
file_report: "../../bin/reports/experiment_statistics_mm10.Rmd"
replicate_report: "../../bin/reports/replicate_statistics.Rmd"
# Centromeres - only relevant for human and not for mouse
#centromeres_bed: "bin/reports/ts171110_hg38_centromeres.bed.gz"

# Statistics
gather_statistics: "bin/statistics/gather_statistics_strainspecific.R"
merge_statistics: "bin/statistics/merge_statistics.R"

# Multiqc
conda_multiqc: ../../bin/multiqc/conda_multiqc.yaml


###############################################################################
### WASP strain specific config ###############################################
###############################################################################

# Note: I have integrated the WASP snakefile (from some time ago) in the DamID
# pipeline. Many WASP-specific things are not not required anymore, and 
# commented. In this document, I have added the WASP configuration. The actual
# WASP rules are in a separate document.


# py2 is a hack so that python2 scripts can be called
# by snakemake (which is written in python3). The value should
# be a command to do whatever is needed to setup a python2 environment and
# call the python2 interpreter. Depending on your system configuration,
# this might involve setting the PATH environment variable or
# just calling python2
# "py2" : "PATH=$HOME/anaconda2/bin:$PATH; python ",
#py2: "PATH=/home/t.v.schaik/mydata/miniconda3/envs/WASP_python2/bin:$PATH; python "
# "py2" : "/home/t.v.schaik/mydata/miniconda3/envs/WASP_python2/bin/python",

# WASP directory containing scripts
wasp_dir: "/home/t.v.schaik/mydata/src/WASP/"

# # directory to write all output data files to
# "output_dir" :  "WASP_ts190215_newparsing",

# location of chromInfo file containing chromosome names and lengths
# (can be downloaded from UCSC genome browser)
chrom_info: "/home/t.v.schaik/mydata/data/genomes/mm10/mm10.chrom.sizes"

# directory to read VCF files from (used to write SNP input files)
# "vcf_dir" : "/home/t.v.schaik/mydata/data/genomes/mouse_assemblies/WASP",
# vcf_dir: "/home/t.v.schaik/mydata/data/genomes/mouse_assemblies/WASP"

# OLD way: directory to write SNP plain text input files to
snp_dir: "/home/t.v.schaik/mydata/data/genomes/mouse_assemblies/WASP/SNP_tables"

## directory to write SNP HDF5 input files to
#snp_h5_dir: "WASP_output/SNPs"

# path to samtools
samtools: "samtools"

## path to bowtie2 aligner
#bowtie2: "bowtie2"

## prefix for bowtie2 reference genome index
#bowtie2_index : "/home/t.v.schaik/mydata/data/genomes/mouse_assemblies/bowtie2_index/GRCm38_68"

# WASP conda
conda_WASP: "../../bin/WASP/conda_WASP.yaml"

# split genomes - custom function to split genomes based on SNP presence
split_genomes: "bin/WASP/split_bam_genomes.py"


###############################################################################
### Input and output ##########################################################
###############################################################################

# Note #1: use spaces instead of tabs for some reason!

# Output directories
output_dir: "results_mm10_nextseq_strainspecific"

out_fastqc: fastqc
out_fastqc_parsed: fastqc_parsed
out_parse: parsed
out_map: mapped
out_count: counts
out_norm: normalized
out_tracks_norm: tracks/normalized
out_tracks_counts: tracks/counts
out_hmm: "HMM"
out_report_experiment: "reports/experiment"
out_report_replicate: "reports/replicate"
out_statistics: statistics
out_multiqc: multiqc

out_WASP: "WASP_tmp"
out_map_strainspecific: "mapped_strainspecific"


# Basename target to basename dam-only control list
basenames:

  #####################################
  ### Test ############################
  #####################################

  # ts220420 - MiSeq Nano test data
  WT_r1_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_1_WT_1_Dam_GTGCTATCGA-CGGTGCTTAA_S2_R1_001.fastq.gz
  WT_r1_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_2_WT_1_LB1_AGAACCTACA-ACCGTACACT_S5_R1_001.fastq.gz
  WT_r2_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_3_WT_2_Dam_ATGGTGTATC-CCACAATTGC_S4_R1_001.fastq.gz
  WT_r2_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_4_WT_2_LB1_CTCAGAATTC-CGGTCTCTGT_S8_R1_001.fastq.gz

  HyTK_r1_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_5_HyTK_1_Dam_TATGATGCAG-CAACTGGCCT_S9_R1_001.fastq.gz
  HyTK_r1_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_6_HyTK_1_LB1_GTGGAGGTAG-GTGACGCGAT_S7_R1_001.fastq.gz
  HyTK_r2_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_7_HyTK_2_Dam_AGAGGCACGA-AATTCCACGT_S12_R1_001.fastq.gz
  HyTK_r2_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_8_HyTK_2_LB1_TTGGCTCCAA-CGGATCAGAC_S13_R1_001.fastq.gz

  F_Ec_cl7_r1_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_9_F_Ec_cl7_1_Dam_TTAAGTGCGT-AGCGACAGGT_S14_R1_001.fastq.gz
  F_Ec_cl7_r1_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_10_F_Ec_cl7_1_LB1_TCGGAGACCT-GAGTAACCTT_S11_R1_001.fastq.gz
  F_Ec_cl7_r2_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_11_F_Ec_cl7_2_Dam_TCCAGCGAAG-GACATAGAAC_S19_R1_001.fastq.gz
  F_Ec_cl7_r2_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_12_F_Ec_cl7_2_LB1_GTACTAAGAG-ATCTAGAGCG_S17_R1_001.fastq.gz

  F_Ec_cl9_r1_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_13_F_Ec_cl9_1_Dam_GTCTTCTCGA-GTTGGCACCA_S18_R1_001.fastq.gz
  F_Ec_cl9_r1_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_14_F_Ec_cl9_1_LB1_ATACACAGAG-CCTTCTGACT_S16_R1_001.fastq.gz
  F_Ec_cl9_r2_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_15_F_Ec_cl9_2_Dam_AGGTCTATGG-GTTCTCACGG_S1_R1_001.fastq.gz
  F_Ec_cl9_r2_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_16_F_Ec_cl9_2_LB1_ACCTCATTGA-AGATCGGATA_S3_R1_001.fastq.gz

  F_L1_cl6_r1_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_17_F_L1_cl6_1_Dam_CGTGGCAGAA-CATCGGAAGA_S6_R1_001.fastq.gz
  F_L1_cl6_r1_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_18_F_L1_cl6_1_LB1_CAACAGGTAG-CACTATCGTC_S20_R1_001.fastq.gz
  F_L1_cl6_r2_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_19_F_L1_cl6_2_Dam_TGATTCCACA-ACGGCTAGAG_S10_R1_001.fastq.gz
  F_L1_cl6_r2_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_20_F_L1_cl6_2_LB1_TAAGGCGATC-TTGTGCTAAC_S21_R1_001.fastq.gz

  F_L1_cl7_r1_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_21_F_L1_cl7_1_Dam_AATCCAGGAT-ACTCTGCATG_S22_R1_001.fastq.gz
  F_L1_cl7_r1_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_22_F_L1_cl7_1_LB1_AAGGTACCGT-ACAAGATCAG_S15_R1_001.fastq.gz
  F_L1_cl7_r2_Dam:
    - /shared/gcf/c.moene/6851/fastq_files/6851_23_F_L1_cl7_2_Dam_ACGACAATGA-CTACCGCGTT_S23_R1_001.fastq.gz
  F_L1_cl7_r2_LB1:
    - /shared/gcf/c.moene/6851/fastq_files/6851_24_F_L1_cl7_2_LB1_TGCGTTCTGC-GAGCGACCAA_S24_R1_001.fastq.gz





# Bam control list, using basenames only
dam_controls:

  # Test data
  WT_r1_LB1: WT_r1_Dam
  WT_r2_LB1: WT_r2_Dam

  HyTK_r1_LB1: HyTK_r1_Dam
  HyTK_r2_LB1: HyTK_r2_Dam

  F_Ec_cl7_r1_LB1: F_Ec_cl7_r1_Dam
  F_Ec_cl7_r2_LB1: F_Ec_cl7_r2_Dam

  F_Ec_cl9_r1_LB1: F_Ec_cl9_r1_Dam
  F_Ec_cl9_r2_LB1: F_Ec_cl9_r2_Dam

  F_L1_cl6_r1_LB1: F_L1_cl6_r1_Dam
  F_L1_cl6_r2_LB1: F_L1_cl6_r2_Dam

  F_L1_cl7_r1_LB1: F_L1_cl7_r1_Dam
  F_L1_cl7_r2_LB1: F_L1_cl7_r2_Dam


# Replicate experiments
replicates:

  WT_LB1:
    - WT_r1_LB1
    - WT_r2_LB1
  HyTK_LB1:
    - HyTK_r1_LB1
    - HyTK_r2_LB1
  F_Ec_cl7_LB1:
    - F_Ec_cl7_r1_LB1
    - F_Ec_cl7_r2_LB1
  F_Ec_cl9_LB1:
    - F_Ec_cl9_r1_LB1
    - F_Ec_cl9_r2_LB1
  F_L1_cl6_LB1:
    - F_L1_cl6_r1_LB1
    - F_L1_cl6_r2_LB1
  F_L1_cl7_LB1:
    - F_L1_cl7_r1_LB1
    - F_L1_cl7_r2_LB1


