---
title: "Figure_Supp_2_LD20230713_deletion_serie"
date: "2023-06-13"
output: 
  html_document:
    theme: journal #cerulean
    highlight: monochrome
    toc: true
    toc_float: true
    code_folding: show
  editor_options:
    chunk_output_type: console
---

Scripts for all figures in the paper.
This is Figure Supp 2

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load libraries
```{r}
suppressWarnings(library(GenomicRanges))
suppressWarnings(library(dplyr))
suppressWarnings(library(stringr))
suppressWarnings(library(readr))
suppressWarnings(library(tidyr))
suppressWarnings(library(ggplot2))
suppressWarnings(library(ggplotify))
library(rtracklayer)
library(IRanges)
library(GenomeInfoDb)
library(tidyverse)
library(ggrastr)
library(gridExtra)
library(colorspace)
library(caTools)
library(RColorBrewer)
```




# Figure Supp 2A - Deletions on the CAST allele
```{r}
# Load data
LoadData <- function(samples, directory = "counts", column = "sample", bin_size = "25kb", 
                     results_dir = "/DATA/usr/l.dauban/projects/pA-DamID/E1972_pA-Dam_rec_clones") {
  # Simply load the normalized values and return one GRanges object with all
  # the data
  #
  # Input:
  # * samples: samples vector
  # * directory: directory containing the data
  # * column: column name with the sample names
  #
  # Output:
  # * GRanges with data
 
  df.norm <- NULL
 
  for (s in samples) {
   
    # Create the file path of the sample
    df.name <- file.path(results_dir,
                         "results_mm10_nextseq_strainspecific", directory,
                         paste0("bin-", bin_size),
                         paste0(s,
                                ifelse(directory == "normalized",
                                       ".norm.txt.gz",
                                       ".counts.txt.gz")))
   
    # Read the data
    print(df.name)
    df <- read.table(df.name,
                     sep = "\t", stringsAsFactors = FALSE,
                     col.names = c("seqnames", "start", "end", s))
   
    # Add this to one data frame
    if (is.null(df.norm)) {
      df.norm <- df
    } else {
      df.norm <- cbind(df.norm, df[, 4], stringsAsFactors = F)
    }
  }
  
 
  # Add +1 to the start, as this was bed-based
  df.norm[, 2] <- df.norm[, 2] + 1
  
  # Change names
  names(df.norm)[4:ncol(df.norm)] <- samples
 
  # And convert to GRanges
  df.norm <- as(df.norm, "GRanges")
  df.norm
 
}

samples <- c("T201h179r28_1_Dam_129S1-25kb",
             "T201h179r28_2_Dam_129S1-25kb",
             "T201h179r28_1_Dam_CAS-25kb",
             "T201h179r28_2_Dam_CAS-25kb",
             "T201h179r28_1_LB1_129S1-25kb",
             "T201h179r28_2_LB1_129S1-25kb",
             "T201h179r28_1_LB1_CAS-25kb",
             "T201h179r28_2_LB1_CAS-25kb",
             "T201h179r29_1_Dam_129S1-25kb",
             "T201h179r29_2_Dam_129S1-25kb",
             "T201h179r29_1_Dam_CAS-25kb",
             "T201h179r29_2_Dam_CAS-25kb",
             "T201h179r29_1_LB1_129S1-25kb",
             "T201h179r29_2_LB1_129S1-25kb",
             "T201h179r29_1_LB1_CAS-25kb",
             "T201h179r29_2_LB1_CAS-25kb",
             "T201h44r3_1_Dam_129S1-25kb",
             "T201h44r3_2_Dam_129S1-25kb",
             "T201h44r3_1_Dam_CAS-25kb",
             "T201h44r3_2_Dam_CAS-25kb",
             "T201h44r3_1_LB1_129S1-25kb",
             "T201h44r3_2_LB1_129S1-25kb",
             "T201h44r3_1_LB1_CAS-25kb",
             "T201h44r3_2_LB1_CAS-25kb",
             "T201h44r14_1_Dam_129S1-25kb",
             "T201h44r14_2_Dam_129S1-25kb",
             "T201h44r14_1_Dam_CAS-25kb",
             "T201h44r14_2_Dam_CAS-25kb",
             "T201h44r14_1_LB1_129S1-25kb",
             "T201h44r14_2_LB1_129S1-25kb",
             "T201h44r14_1_LB1_CAS-25kb",
             "T201h44r14_2_LB1_CAS-25kb",
             "T201h65r12_1_Dam_129S1-25kb",
             "T201h65r12_2_Dam_129S1-25kb",
             "T201h65r12_1_Dam_CAS-25kb",
             "T201h65r12_2_Dam_CAS-25kb",
             "T201h65r12_1_LB1_129S1-25kb",
             "T201h65r12_2_LB1_129S1-25kb",
             "T201h65r12_1_LB1_CAS-25kb",
             "T201h65r12_2_LB1_CAS-25kb",
             "T201h65r21_1_Dam_129S1-25kb",
             "T201h65r21_2_Dam_129S1-25kb",
             "T201h65r21_1_Dam_CAS-25kb",
             "T201h65r21_2_Dam_CAS-25kb",
             "T201h65r21_1_LB1_129S1-25kb",
             "T201h65r21_2_LB1_129S1-25kb",
             "T201h65r21_1_LB1_CAS-25kb",
             "T201h65r21_2_LB1_CAS-25kb",
             "T201h162r1_2_Dam_129S1-25kb",
             "T201h162r1_2_Dam_CAS-25kb",
             "T201h162r1_2_LB1_129S1-25kb",
             "T201h162r1_2_LB1_CAS-25kb",
             "T201h162r6_1_Dam_129S1-25kb",
             "T201h162r6_2_Dam_129S1-25kb",
             "T201h162r6_1_Dam_CAS-25kb",
             "T201h162r6_2_Dam_CAS-25kb",
             "T201h162r6_1_LB1_129S1-25kb",
             "T201h162r6_2_LB1_129S1-25kb",
             "T201h162r6_1_LB1_CAS-25kb",
             "T201h162r6_2_LB1_CAS-25kb",
             "T201h24r2_1_Dam_129S1-25kb",
             "T201h24r2_2_Dam_129S1-25kb",
             "T201h24r2_1_Dam_CAS-25kb",
             "T201h24r2_2_Dam_CAS-25kb",
             "T201h24r2_1_LB1_129S1-25kb",
             "T201h24r2_2_LB1_129S1-25kb",
             "T201h24r2_1_LB1_CAS-25kb",
             "T201h24r2_2_LB1_CAS-25kb",
             "T201h24r11_2_Dam_129S1-25kb",
             "T201h24r11_2_Dam_CAS-25kb",
             "T201h24r11_2_LB1_129S1-25kb",
             "T201h24r11_2_LB1_CAS-25kb",
             "T48h20r8_1_Dam_129S1-25kb",
             "T48h20r8_2_Dam_129S1-25kb",
             "T48h20r8_1_Dam_CAS-25kb",
             "T48h20r8_2_Dam_CAS-25kb",
             "T48h20r8_1_LB1_129S1-25kb",
             "T48h20r8_2_LB1_129S1-25kb",
             "T48h20r8_1_LB1_CAS-25kb",
             "T48h20r8_2_LB1_CAS-25kb",
             "T48h20r16_1_Dam_129S1-25kb",
             "T48h20r16_2_Dam_129S1-25kb",
             "T48h20r16_1_Dam_CAS-25kb",
             "T48h20r16_2_Dam_CAS-25kb",
             "T48h20r16_1_LB1_129S1-25kb",
             "T48h20r16_2_LB1_129S1-25kb",
             "T48h20r16_1_LB1_CAS-25kb",
             "T48h20r16_2_LB1_CAS-25kb")


samples <- LoadData(samples)
samples <- samples %>% as_tibble() %>% rowwise() %>% mutate(T201h179r28_129 = sum(T201h179r28_1_Dam_129S1.25kb, T201h179r28_2_Dam_129S1.25kb, T201h179r28_1_LB1_129S1.25kb, T201h179r28_2_LB1_129S1.25kb),
                                                            T201h179r28_CAST = sum(T201h179r28_1_Dam_CAS.25kb, T201h179r28_2_Dam_CAS.25kb, T201h179r28_1_LB1_CAS.25kb, T201h179r28_2_LB1_CAS.25kb),
                                                            T201h179r29_129 = sum(T201h179r29_1_Dam_129S1.25kb, T201h179r29_2_Dam_129S1.25kb, T201h179r29_1_LB1_129S1.25kb, T201h179r29_2_LB1_129S1.25kb),
                                                            T201h179r29_CAST = sum(T201h179r29_1_Dam_CAS.25kb, T201h179r29_2_Dam_CAS.25kb, T201h179r29_1_LB1_CAS.25kb, T201h179r29_2_LB1_CAS.25kb),
                                                            T201h44r3_129 = sum(T201h44r3_1_Dam_129S1.25kb, T201h44r3_2_Dam_129S1.25kb, T201h44r3_1_LB1_129S1.25kb, T201h44r3_2_LB1_129S1.25kb),
                                                            T201h44r3_CAST = sum(T201h44r3_1_Dam_CAS.25kb, T201h44r3_2_Dam_CAS.25kb, T201h44r3_1_LB1_CAS.25kb, T201h44r3_2_LB1_CAS.25kb),
                                                            T201h44r14_129 = sum(T201h44r14_1_Dam_129S1.25kb, T201h44r14_2_Dam_129S1.25kb, T201h44r14_1_LB1_129S1.25kb, T201h44r14_2_LB1_129S1.25kb),
                                                            T201h44r14_CAST = sum(T201h44r14_1_Dam_CAS.25kb, T201h44r14_2_Dam_CAS.25kb, T201h44r14_1_LB1_CAS.25kb, T201h44r14_2_LB1_CAS.25kb),
                                                            T201h65r12_129 = sum(T201h65r12_1_Dam_129S1.25kb, T201h65r12_2_Dam_129S1.25kb, T201h65r12_1_LB1_129S1.25kb, T201h65r12_2_LB1_129S1.25kb),
                                                            T201h65r12_CAST = sum(T201h65r12_1_Dam_CAS.25kb, T201h65r12_2_Dam_CAS.25kb, T201h65r12_1_LB1_CAS.25kb, T201h65r12_2_LB1_CAS.25kb),
                                                            T201h65r21_129 = sum(T201h65r21_1_Dam_129S1.25kb, T201h65r21_2_Dam_129S1.25kb, T201h65r21_1_LB1_129S1.25kb, T201h65r21_2_LB1_129S1.25kb),
                                                            T201h65r21_CAST = sum(T201h65r21_1_Dam_CAS.25kb, T201h65r21_2_Dam_CAS.25kb, T201h65r21_1_LB1_CAS.25kb, T201h65r21_2_LB1_CAS.25kb),
                                                            T201h162r1_129 = sum(T201h162r1_2_Dam_129S1.25kb, T201h162r1_2_LB1_129S1.25kb),
                                                            T201h162r1_CAST = sum(T201h162r1_2_Dam_CAS.25kb, T201h162r1_2_LB1_CAS.25kb),
                                                            T201h162r6_129 = sum(T201h162r6_1_Dam_129S1.25kb, T201h162r6_2_Dam_129S1.25kb, T201h162r6_1_LB1_129S1.25kb, T201h162r6_2_LB1_129S1.25kb),
                                                            T201h162r6_CAST = sum(T201h162r6_1_Dam_CAS.25kb, T201h162r6_2_Dam_CAS.25kb, T201h162r6_1_LB1_CAS.25kb, T201h162r6_2_LB1_CAS.25kb),
                                                            T201h24r2_129 = sum(T201h24r2_1_Dam_129S1.25kb, T201h24r2_2_Dam_129S1.25kb, T201h24r2_1_LB1_129S1.25kb, T201h24r2_2_LB1_129S1.25kb),
                                                            T201h24r2_CAST = sum(T201h24r2_1_Dam_CAS.25kb, T201h24r2_2_Dam_CAS.25kb, T201h24r2_1_LB1_CAS.25kb, T201h24r2_2_LB1_CAS.25kb),
                                                            T201h24r11_129 = sum(T201h24r11_2_Dam_129S1.25kb, T201h24r11_2_LB1_129S1.25kb),
                                                            T201h24r11_CAST = sum(T201h24r11_2_Dam_CAS.25kb, T201h24r11_2_LB1_CAS.25kb),
                                                            T48h20r8_129 = sum(T48h20r8_1_Dam_129S1.25kb, T48h20r8_2_Dam_129S1.25kb, T48h20r8_1_LB1_129S1.25kb, T48h20r8_2_LB1_129S1.25kb),
                                                            T48h20r8_CAST = sum(T48h20r8_1_Dam_CAS.25kb, T48h20r8_2_Dam_CAS.25kb, T48h20r8_1_LB1_CAS.25kb, T48h20r8_2_LB1_CAS.25kb),
                                                            T48h20r16_129 = sum(T48h20r16_1_Dam_129S1.25kb, T48h20r16_2_Dam_129S1.25kb, T48h20r16_1_LB1_129S1.25kb, T48h20r16_2_LB1_129S1.25kb),
                                                            T48h20r16_CAST = sum(T48h20r16_1_Dam_CAS.25kb, T48h20r16_2_Dam_CAS.25kb, T48h20r16_1_LB1_CAS.25kb, T48h20r16_2_LB1_CAS.25kb)
                                                            )




## coordinates for all clones
del_loc = data.frame(sample = c('179', '44', '65', '162', '24', '20'),
           x = rep(110927601, 6),
           y = rep(1.4, 6),
           xend = c(111711810, 111912792, 112396323, 112440815, 112637307, 112877498),
           yend = rep(1.4,6))


```

# T201h179
```{r}
# Function
PlotDataTracksLight <- function(input_tib, exp_names, color_groups, 
                                centromeres = NULL, plot_chr = "chr1", 
                                plot_start = 1, plot_end = 500e6,
                                smooth = 1, color_list = NULL,
                                fix_yaxis = F, aspect_ratio = NULL,
                                lighten_negative = F, raster = F) {
  
  # Get the scores for the samples
  tib_plot <- input_tib %>%
    dplyr::select(seqnames, start, end, 
                  all_of(exp_names))
  
  if (smooth > 1) {
    tib_plot <- tib_plot %>%
      mutate_at(vars(contains("_")), 
                runmean, k = smooth)
  }
  
  # Filter for plotting window
  tib_plot <- tib_plot %>%
    filter(seqnames == plot_chr,
           start >= plot_start,
           end <= plot_end)
  
  # Gather
  tib_gather <- tib_plot %>%
    gather(key, value, -seqnames, -start, -end) %>%
    mutate(key = factor(key, levels = exp_names),
           fill_column = color_groups[match(key, names(color_groups))],
           fill_column = factor(fill_column, levels = unique(color_groups)))
  
  # If desired, make negative values a lighter shade to improve visualization
  if (lighten_negative) {
    tib_gather <- tib_gather %>%
      mutate(fill_column = interaction(fill_column,
                                       value < 0))
  }
  
  
  
  # Plot
  ylimits <- quantile(tib_gather$value, c(0.001, 0.999), na.rm = T)
  fill_column <- NULL
  
  plt <- tib_gather %>% 
    ggplot(aes(fill = fill_column))
  
  
  # Set all counts tracks to the same limits
  if (raster) {
    plt <- plt + 
      rasterize(geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                              ymin = 0, ymax = value)),
                dpi = 300)
  } else {
    plt <- plt + 
      geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                    ymin = 0, ymax = value))
  }
  
  plt <- plt + 
    geom_hline(yintercept = 0, size = 0.5) +
    #geom_segment(data=del_loc[1,], mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), linewidth = 1, color = "#6BAED6")+
    geom_vline(xintercept = del_loc[1,]$x/1e6, size = 0.5, col = "black", linetype = "dashed") +
    geom_vline(xintercept = del_loc[1,]$xend/1e6, size = 0.5, col = "black", linetype = "dashed") +
    facet_grid(key ~ ., scales = "free_y") +
    xlab(paste0(plot_chr, " (Mb)")) +
    ylab("counts (Dam + LB1)") +
    #scale_x_continuous(expand = c(0, 0)) + 
    #scale_y_continuous(expand = c(0.025, 0.025), limits = c(-1.5, 1.5)) +
    theme_bw() +
    theme(text = element_text(size = 50))
  
  # Centromeres
  if (! is.null(centromeres)) {
    centromeres.plt <- as_tibble(centromeres) %>%
      filter(seqnames == plot_chr) %>%
      gather(key_centromeres, value, start, end)
    
    plt <- plt +
      geom_line(data = centromeres.plt, 
                aes(x = value / 1e6, y = 0),
                color = "black", size = 2)
  }
  
  if (! is.null(color_list)) {
    
    if (lighten_negative) {
      color_list <- c(color_list,
                      lighten(color_list, amount = 0.5))
    }
    
    colors <- levels(tib_gather$fill_column)
    
    color_list <- color_list[1:length(colors)]
    names(color_list) <- colors
    #colors <- recode(colors, !!!color_list)
    
    plt <- plt +
      scale_fill_manual(values = color_list, guide = "none")
  } else {
    plt <- plt +
      scale_fill_brewer(palette = "Set1", guide = "none")
  }
  
  if (fix_yaxis) {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6),
                      ylim = ylimits)
  } else {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6))
  }
  
  if (! is.null(aspect_ratio)) {
    plt <- plt +
      theme(aspect.ratio = aspect_ratio)
  }
  
  plot(plt)
  
}

# Plot
PlotDataTracksLight(input_tib = samples,
                    exp_names = c("T201h179r28_CAST", "T201h179r28_129", "T201h179r29_CAST", "T201h179r29_129"),
                    color_groups = c(T201h179r28_CAST = "pA-DamID", T201h179r28_129 = "pA-DamID", T201h179r29_CAST = "pA-DamID", T201h179r29_129 = "pA-DamID") ,
                    plot_chr = "chr9", plot_start = 110500000, plot_end = 114700000,
                    color_list = c("gray"),
                    #color_list = brewer.pal(3, "Paired"),
                    aspect_ratio = 1/3,
                    smooth = 7,
                    #fix_yaxis = F,
                    lighten_negative = T,
                    raster = T)

ggsave("FigS2A_LD20230717_T201h179.pdf", height = 20, width = 15)


```


# T201h44
```{r}
# Function
PlotDataTracksLight <- function(input_tib, exp_names, color_groups, 
                                centromeres = NULL, plot_chr = "chr1", 
                                plot_start = 1, plot_end = 500e6,
                                smooth = 1, color_list = NULL,
                                fix_yaxis = F, aspect_ratio = NULL,
                                lighten_negative = F, raster = F) {
  
  # Get the scores for the samples
  tib_plot <- input_tib %>%
    dplyr::select(seqnames, start, end, 
                  all_of(exp_names))
  
  if (smooth > 1) {
    tib_plot <- tib_plot %>%
      mutate_at(vars(contains("_")), 
                runmean, k = smooth)
  }
  
  # Filter for plotting window
  tib_plot <- tib_plot %>%
    filter(seqnames == plot_chr,
           start >= plot_start,
           end <= plot_end)
  
  # Gather
  tib_gather <- tib_plot %>%
    gather(key, value, -seqnames, -start, -end) %>%
    mutate(key = factor(key, levels = exp_names),
           fill_column = color_groups[match(key, names(color_groups))],
           fill_column = factor(fill_column, levels = unique(color_groups)))
  
  # If desired, make negative values a lighter shade to improve visualization
  if (lighten_negative) {
    tib_gather <- tib_gather %>%
      mutate(fill_column = interaction(fill_column,
                                       value < 0))
  }
  
  
  
  # Plot
  ylimits <- quantile(tib_gather$value, c(0.001, 0.999), na.rm = T)
  fill_column <- NULL
  
  plt <- tib_gather %>% 
    ggplot(aes(fill = fill_column))
  
  
  # Set all counts tracks to the same limits
  if (raster) {
    plt <- plt + 
      rasterize(geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                              ymin = 0, ymax = value)),
                dpi = 300)
  } else {
    plt <- plt + 
      geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                    ymin = 0, ymax = value))
  }
  
  plt <- plt + 
    geom_hline(yintercept = 0, size = 0.5) +
    #geom_segment(data=del_loc[2,], mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), linewidth = 1, color = "#6BAED6")+
    geom_vline(xintercept = del_loc[2,]$x/1e6, size = 0.5, col = "black", linetype = "dashed") +
    geom_vline(xintercept = del_loc[2,]$xend/1e6, size = 0.5, col = "black", linetype = "dashed") +
    facet_grid(key ~ ., scales = "free_y") +
    xlab(paste0(plot_chr, " (Mb)")) +
    ylab("counts (Dam + LB1)") +
    #scale_x_continuous(expand = c(0, 0)) + 
    #scale_y_continuous(expand = c(0.025, 0.025), limits = c(-1.5, 1.5)) +
    theme_bw() +
    theme(text = element_text(size = 50))

  
  # Centromeres
  if (! is.null(centromeres)) {
    centromeres.plt <- as_tibble(centromeres) %>%
      filter(seqnames == plot_chr) %>%
      gather(key_centromeres, value, start, end)
    
    plt <- plt +
      geom_line(data = centromeres.plt, 
                aes(x = value / 1e6, y = 0),
                color = "black", size = 2)
  }
  
  if (! is.null(color_list)) {
    
    if (lighten_negative) {
      color_list <- c(color_list,
                      lighten(color_list, amount = 0.5))
    }
    
    colors <- levels(tib_gather$fill_column)
    
    color_list <- color_list[1:length(colors)]
    names(color_list) <- colors
    #colors <- recode(colors, !!!color_list)
    
    plt <- plt +
      scale_fill_manual(values = color_list, guide = "none")
  } else {
    plt <- plt +
      scale_fill_brewer(palette = "Set1", guide = "none")
  }
  
  if (fix_yaxis) {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6),
                      ylim = ylimits)
  } else {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6))
  }
  
  if (! is.null(aspect_ratio)) {
    plt <- plt +
      theme(aspect.ratio = aspect_ratio)
  }
  
  plot(plt)
  
}

# Plot
T201h44.track.plot = PlotDataTracksLight(input_tib = samples,
                    exp_names = c("T201h44r3_CAST", "T201h44r3_129", "T201h44r14_CAST", "T201h44r14_129"),
                    color_groups = c(`T201h44r3_CAST` = "pA-DamID", `T201h44r3_129` = "pA-DamID", `T201h44r14_CAST` = "pA-DamID", `T201h44r14_129` = "pA-DamID") ,
                    plot_chr = "chr9", plot_start = 110500000, plot_end = 114700000,
                    color_list = c("gray"),
                    #color_list = brewer.pal(3, "Paired"),
                    aspect_ratio = 1/3,
                    smooth = 7,
                    #fix_yaxis = F,
                    lighten_negative = T,
                    raster = T)

ggsave("FigS2B_LD20230717_T201h44.pdf", height = 20, width = 15)

```


# T201h65
```{r}
# Function
PlotDataTracksLight <- function(input_tib, exp_names, color_groups, 
                                centromeres = NULL, plot_chr = "chr1", 
                                plot_start = 1, plot_end = 500e6,
                                smooth = 1, color_list = NULL,
                                fix_yaxis = F, aspect_ratio = NULL,
                                lighten_negative = F, raster = F) {
  
  # Get the scores for the samples
  tib_plot <- input_tib %>%
    dplyr::select(seqnames, start, end, 
                  all_of(exp_names))
  
  if (smooth > 1) {
    tib_plot <- tib_plot %>%
      mutate_at(vars(contains("_")), 
                runmean, k = smooth)
  }
  
  # Filter for plotting window
  tib_plot <- tib_plot %>%
    filter(seqnames == plot_chr,
           start >= plot_start,
           end <= plot_end)
  
  # Gather
  tib_gather <- tib_plot %>%
    gather(key, value, -seqnames, -start, -end) %>%
    mutate(key = factor(key, levels = exp_names),
           fill_column = color_groups[match(key, names(color_groups))],
           fill_column = factor(fill_column, levels = unique(color_groups)))
  
  # If desired, make negative values a lighter shade to improve visualization
  if (lighten_negative) {
    tib_gather <- tib_gather %>%
      mutate(fill_column = interaction(fill_column,
                                       value < 0))
  }
  
  
  
  # Plot
  ylimits <- quantile(tib_gather$value, c(0.001, 0.999), na.rm = T)
  fill_column <- NULL
  
  plt <- tib_gather %>% 
    ggplot(aes(fill = fill_column))
  
  
  # Set all counts tracks to the same limits
  if (raster) {
    plt <- plt + 
      rasterize(geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                              ymin = 0, ymax = value)),
                dpi = 300)
  } else {
    plt <- plt + 
      geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                    ymin = 0, ymax = value))
  }
  
  plt <- plt + 
    geom_hline(yintercept = 0, size = 0.5) +
    #geom_segment(data=del_loc[3,], mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), linewidth = 1, color = "#6BAED6")+
    geom_vline(xintercept = del_loc[3,]$x/1e6, size = 0.5, col = "black", linetype = "dashed") +
    geom_vline(xintercept = del_loc[3,]$xend/1e6, size = 0.5, col = "black", linetype = "dashed") +
    facet_grid(key ~ ., scales = "free_y") +
    xlab(paste0(plot_chr, " (Mb)")) +
    ylab("counts (Dam + LB1)") +
    #scale_x_continuous(expand = c(0, 0)) + 
    #scale_y_continuous(expand = c(0.025, 0.025), limits = c(-1.5, 1.5)) +
    theme_bw() +
    theme(text = element_text(size = 50))
  
  # Centromeres
  if (! is.null(centromeres)) {
    centromeres.plt <- as_tibble(centromeres) %>%
      filter(seqnames == plot_chr) %>%
      gather(key_centromeres, value, start, end)
    
    plt <- plt +
      geom_line(data = centromeres.plt, 
                aes(x = value / 1e6, y = 0),
                color = "black", size = 2)
  }
  
  if (! is.null(color_list)) {
    
    if (lighten_negative) {
      color_list <- c(color_list,
                      lighten(color_list, amount = 0.5))
    }
    
    colors <- levels(tib_gather$fill_column)
    
    color_list <- color_list[1:length(colors)]
    names(color_list) <- colors
    #colors <- recode(colors, !!!color_list)
    
    plt <- plt +
      scale_fill_manual(values = color_list, guide = "none")
  } else {
    plt <- plt +
      scale_fill_brewer(palette = "Set1", guide = "none")
  }
  
  if (fix_yaxis) {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6),
                      ylim = ylimits)
  } else {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6))
  }
  
  if (! is.null(aspect_ratio)) {
    plt <- plt +
      theme(aspect.ratio = aspect_ratio)
  }
  
  plot(plt)
  
}

# Plot
T201h65.track.plot = PlotDataTracksLight(input_tib = samples,
                    exp_names = c("T201h65r12_CAST", "T201h65r12_129", "T201h65r21_CAST", "T201h65r21_129"),
                    color_groups = c(`T201h65r12_CAST` = "pA-DamID", `T201h65r12_129` = "pA-DamID", `T201h65r21_CAST` = "pA-DamID", `T201h65r21_129` = "pA-DamID") ,
                    plot_chr = "chr9", plot_start = 110500000, plot_end = 114700000,
                    color_list = c("gray"),
                    #color_list = brewer.pal(3, "Paired"),
                    aspect_ratio = 1/3,
                    smooth = 7,
                    #fix_yaxis = F,
                    lighten_negative = T,
                    raster = T)

ggsave("FigS2C_LD20230717_T201h65.pdf", height = 20, width = 15)

```



# T201h162
```{r}
# Function
PlotDataTracksLight <- function(input_tib, exp_names, color_groups, 
                                centromeres = NULL, plot_chr = "chr1", 
                                plot_start = 1, plot_end = 500e6,
                                smooth = 1, color_list = NULL,
                                fix_yaxis = F, aspect_ratio = NULL,
                                lighten_negative = F, raster = F) {
  
  # Get the scores for the samples
  tib_plot <- input_tib %>%
    dplyr::select(seqnames, start, end, 
                  all_of(exp_names))
  
  if (smooth > 1) {
    tib_plot <- tib_plot %>%
      mutate_at(vars(contains("_")), 
                runmean, k = smooth)
  }
  
  # Filter for plotting window
  tib_plot <- tib_plot %>%
    filter(seqnames == plot_chr,
           start >= plot_start,
           end <= plot_end)
  
  # Gather
  tib_gather <- tib_plot %>%
    gather(key, value, -seqnames, -start, -end) %>%
    mutate(key = factor(key, levels = exp_names),
           fill_column = color_groups[match(key, names(color_groups))],
           fill_column = factor(fill_column, levels = unique(color_groups)))
  
  # If desired, make negative values a lighter shade to improve visualization
  if (lighten_negative) {
    tib_gather <- tib_gather %>%
      mutate(fill_column = interaction(fill_column,
                                       value < 0))
  }
  
  
  
  # Plot
  ylimits <- quantile(tib_gather$value, c(0.001, 0.999), na.rm = T)
  fill_column <- NULL
  
  plt <- tib_gather %>% 
    ggplot(aes(fill = fill_column))
  
  
  # Set all counts tracks to the same limits
  if (raster) {
    plt <- plt + 
      rasterize(geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                              ymin = 0, ymax = value)),
                dpi = 300)
  } else {
    plt <- plt + 
      geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                    ymin = 0, ymax = value))
  }
  
  plt <- plt + 
    geom_hline(yintercept = 0, size = 0.5) +
    #geom_segment(data=del_loc[4,], mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), linewidth = 1, color = "#6BAED6")+
    geom_vline(xintercept = del_loc[4,]$x/1e6, size = 0.5, col = "black", linetype = "dashed") +
    geom_vline(xintercept = del_loc[4,]$xend/1e6, size = 0.5, col = "black", linetype = "dashed") +
    facet_grid(key ~ ., scales = "free_y") +
    xlab(paste0(plot_chr, " (Mb)")) +
    ylab("counts (Dam + LB1)") +
    #scale_x_continuous(expand = c(0, 0)) + 
    #scale_y_continuous(expand = c(0.025, 0.025), limits = c(-1.5, 1.5)) +
    theme_bw() +
    theme(text = element_text(size = 50))
  
  # Centromeres
  if (! is.null(centromeres)) {
    centromeres.plt <- as_tibble(centromeres) %>%
      filter(seqnames == plot_chr) %>%
      gather(key_centromeres, value, start, end)
    
    plt <- plt +
      geom_line(data = centromeres.plt, 
                aes(x = value / 1e6, y = 0),
                color = "black", size = 2)
  }
  
  if (! is.null(color_list)) {
    
    if (lighten_negative) {
      color_list <- c(color_list,
                      lighten(color_list, amount = 0.5))
    }
    
    colors <- levels(tib_gather$fill_column)
    
    color_list <- color_list[1:length(colors)]
    names(color_list) <- colors
    #colors <- recode(colors, !!!color_list)
    
    plt <- plt +
      scale_fill_manual(values = color_list, guide = "none")
  } else {
    plt <- plt +
      scale_fill_brewer(palette = "Set1", guide = "none")
  }
  
  if (fix_yaxis) {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6),
                      ylim = ylimits)
  } else {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6))
  }
  
  if (! is.null(aspect_ratio)) {
    plt <- plt +
      theme(aspect.ratio = aspect_ratio)
  }
  
  plot(plt)
  
}

# Plot
T201h162.track.plot = PlotDataTracksLight(input_tib = samples,
                    exp_names = c("T201h162r1_CAST", "T201h162r1_129", "T201h162r6_CAST", "T201h162r6_129"),
                    color_groups = c(`T201h162r1_CAST` = "pA-DamID", `T201h162r1_129` = "pA-DamID", `T201h162r6_CAST` = "pA-DamID", `T201h162r6_129` = "pA-DamID") ,
                    plot_chr = "chr9", plot_start = 110500000, plot_end = 114700000,
                    color_list = c("gray"),
                    #color_list = brewer.pal(3, "Paired"),
                    aspect_ratio = 1/3,
                    smooth = 7,
                    #fix_yaxis = F,
                    lighten_negative = T,
                    raster = T)

ggsave("FigS2D_LD20230717_T201h162.pdf", height = 20, width = 15)

```



# T201h24
```{r}
# Function
PlotDataTracksLight <- function(input_tib, exp_names, color_groups, 
                                centromeres = NULL, plot_chr = "chr1", 
                                plot_start = 1, plot_end = 500e6,
                                smooth = 1, color_list = NULL,
                                fix_yaxis = F, aspect_ratio = NULL,
                                lighten_negative = F, raster = F) {
  
  # Get the scores for the samples
  tib_plot <- input_tib %>%
    dplyr::select(seqnames, start, end, 
                  all_of(exp_names))
  
  if (smooth > 1) {
    tib_plot <- tib_plot %>%
      mutate_at(vars(contains("_")), 
                runmean, k = smooth)
  }
  
  # Filter for plotting window
  tib_plot <- tib_plot %>%
    filter(seqnames == plot_chr,
           start >= plot_start,
           end <= plot_end)
  
  # Gather
  tib_gather <- tib_plot %>%
    gather(key, value, -seqnames, -start, -end) %>%
    mutate(key = factor(key, levels = exp_names),
           fill_column = color_groups[match(key, names(color_groups))],
           fill_column = factor(fill_column, levels = unique(color_groups)))
  
  # If desired, make negative values a lighter shade to improve visualization
  if (lighten_negative) {
    tib_gather <- tib_gather %>%
      mutate(fill_column = interaction(fill_column,
                                       value < 0))
  }
  
  
  
  # Plot
  ylimits <- quantile(tib_gather$value, c(0.001, 0.999), na.rm = T)
  fill_column <- NULL
  
  plt <- tib_gather %>% 
    ggplot(aes(fill = fill_column))
  
  
  # Set all counts tracks to the same limits
  if (raster) {
    plt <- plt + 
      rasterize(geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                              ymin = 0, ymax = value)),
                dpi = 300)
  } else {
    plt <- plt + 
      geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                    ymin = 0, ymax = value))
  }
  
  plt <- plt + 
    geom_hline(yintercept = 0, size = 0.5) +
    #geom_segment(data=del_loc[5,], mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), linewidth = 1, color = "#6BAED6")+
    geom_vline(xintercept = del_loc[5,]$x/1e6, size = 0.5, col = "black", linetype = "dashed") +
    geom_vline(xintercept = del_loc[5,]$xend/1e6, size = 0.5, col = "black", linetype = "dashed") +
    facet_grid(key ~ ., scales = "free_y") +
    xlab(paste0(plot_chr, " (Mb)")) +
    ylab("counts (Dam + LB1)") +
    #scale_x_continuous(expand = c(0, 0)) + 
    #scale_y_continuous(expand = c(0.025, 0.025), limits = c(-1.5, 1.5)) +
    theme_bw() +
    theme(text = element_text(size = 50))
  
  # Centromeres
  if (! is.null(centromeres)) {
    centromeres.plt <- as_tibble(centromeres) %>%
      filter(seqnames == plot_chr) %>%
      gather(key_centromeres, value, start, end)
    
    plt <- plt +
      geom_line(data = centromeres.plt, 
                aes(x = value / 1e6, y = 0),
                color = "black", size = 2)
  }
  
  if (! is.null(color_list)) {
    
    if (lighten_negative) {
      color_list <- c(color_list,
                      lighten(color_list, amount = 0.5))
    }
    
    colors <- levels(tib_gather$fill_column)
    
    color_list <- color_list[1:length(colors)]
    names(color_list) <- colors
    #colors <- recode(colors, !!!color_list)
    
    plt <- plt +
      scale_fill_manual(values = color_list, guide = "none")
  } else {
    plt <- plt +
      scale_fill_brewer(palette = "Set1", guide = "none")
  }
  
  if (fix_yaxis) {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6),
                      ylim = ylimits)
  } else {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6))
  }
  
  if (! is.null(aspect_ratio)) {
    plt <- plt +
      theme(aspect.ratio = aspect_ratio)
  }
  
  plot(plt)
  
}

# Plot
T201h24.track.plot = PlotDataTracksLight(input_tib = samples,
                    exp_names = c("T201h24r2_CAST", "T201h24r2_129", "T201h24r11_CAST", "T201h24r11_129"),
                    color_groups = c(`T201h24r2_CAST` = "pA-DamID", `T201h24r2_129` = "pA-DamID", `T201h24r11_CAST` = "pA-DamID", `T201h24r11_129` = "pA-DamID") ,
                    plot_chr = "chr9", plot_start = 110500000, plot_end = 114700000,
                    color_list = c("gray"),
                    #color_list = brewer.pal(3, "Paired"),
                    aspect_ratio = 1/3,
                    smooth = 7,
                    #fix_yaxis = F,
                    lighten_negative = T,
                    raster = T)

ggsave("FigS2E_LD20230717_T201h24.pdf", height = 20, width = 15)

```


# T48h20
```{r}
# Function
PlotDataTracksLight <- function(input_tib, exp_names, color_groups, 
                                centromeres = NULL, plot_chr = "chr1", 
                                plot_start = 1, plot_end = 500e6,
                                smooth = 1, color_list = NULL,
                                fix_yaxis = F, aspect_ratio = NULL,
                                lighten_negative = F, raster = F) {
  
  # Get the scores for the samples
  tib_plot <- input_tib %>%
    dplyr::select(seqnames, start, end, 
                  all_of(exp_names))
  
  if (smooth > 1) {
    tib_plot <- tib_plot %>%
      mutate_at(vars(contains("_")), 
                runmean, k = smooth)
  }
  
  # Filter for plotting window
  tib_plot <- tib_plot %>%
    filter(seqnames == plot_chr,
           start >= plot_start,
           end <= plot_end)
  
  # Gather
  tib_gather <- tib_plot %>%
    gather(key, value, -seqnames, -start, -end) %>%
    mutate(key = factor(key, levels = exp_names),
           fill_column = color_groups[match(key, names(color_groups))],
           fill_column = factor(fill_column, levels = unique(color_groups)))
  
  # If desired, make negative values a lighter shade to improve visualization
  if (lighten_negative) {
    tib_gather <- tib_gather %>%
      mutate(fill_column = interaction(fill_column,
                                       value < 0))
  }
  
  
  
  # Plot
  ylimits <- quantile(tib_gather$value, c(0.001, 0.999), na.rm = T)
  fill_column <- NULL
  
  plt <- tib_gather %>% 
    ggplot(aes(fill = fill_column))
  
  
  # Set all counts tracks to the same limits
  if (raster) {
    plt <- plt + 
      rasterize(geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                              ymin = 0, ymax = value)),
                dpi = 300)
  } else {
    plt <- plt + 
      geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                    ymin = 0, ymax = value))
  }
  
  plt <- plt + 
    geom_hline(yintercept = 0, size = 0.5) +
    #geom_segment(data=del_loc[6,], mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), linewidth = 1, color = "#6BAED6")+
    geom_vline(xintercept = del_loc[6,]$x/1e6, size = 0.5, col = "black", linetype = "dashed") +
    geom_vline(xintercept = del_loc[6,]$xend/1e6, size = 0.5, col = "black", linetype = "dashed") +
    facet_grid(key ~ ., scales = "free_y") +
    xlab(paste0(plot_chr, " (Mb)")) +
    ylab("counts (Dam + LB1)") +
    #scale_x_continuous(expand = c(0, 0)) + 
    #scale_y_continuous(expand = c(0.025, 0.025), limits = c(-1.5, 1.5)) +
    theme_bw() +
    theme(text = element_text(size = 50))
  
  # Centromeres
  if (! is.null(centromeres)) {
    centromeres.plt <- as_tibble(centromeres) %>%
      filter(seqnames == plot_chr) %>%
      gather(key_centromeres, value, start, end)
    
    plt <- plt +
      geom_line(data = centromeres.plt, 
                aes(x = value / 1e6, y = 0),
                color = "black", size = 2)
  }
  
  if (! is.null(color_list)) {
    
    if (lighten_negative) {
      color_list <- c(color_list,
                      lighten(color_list, amount = 0.5))
    }
    
    colors <- levels(tib_gather$fill_column)
    
    color_list <- color_list[1:length(colors)]
    names(color_list) <- colors
    #colors <- recode(colors, !!!color_list)
    
    plt <- plt +
      scale_fill_manual(values = color_list, guide = "none")
  } else {
    plt <- plt +
      scale_fill_brewer(palette = "Set1", guide = "none")
  }
  
  if (fix_yaxis) {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6),
                      ylim = ylimits)
  } else {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6))
  }
  
  if (! is.null(aspect_ratio)) {
    plt <- plt +
      theme(aspect.ratio = aspect_ratio)
  }
  
  plot(plt)
  
}

# Plot
T48h20.track.plot = PlotDataTracksLight(input_tib = samples,
                    exp_names = c("T48h20r8_CAST", "T48h20r8_129", "T48h20r16_CAST", "T48h20r16_129"),
                    color_groups = c(`T48h20r8_CAST` = "pA-DamID", `T48h20r8_129` = "pA-DamID", `T48h20r16_CAST` = "pA-DamID", `T48h20r16_129` = "pA-DamID") ,
                    plot_chr = "chr9", plot_start = 110500000, plot_end = 114700000,
                    color_list = c("gray"),
                    #color_list = brewer.pal(3, "Paired"),
                    aspect_ratio = 1/3,
                    smooth = 7,
                    #fix_yaxis = F,
                    lighten_negative = T,
                    raster = T)

ggsave("FigS2F_LD20230717_T48h20.pdf", height = 20, width = 15)

```



