---
title: "Figure3_LD20231218_LAD1_boosting_region"
date: "2023-12-18"
output: 
  html_document:
    theme: journal #cerulean
    highlight: monochrome
    toc: true
    toc_float: true
    code_folding: show
  editor_options:
    chunk_output_type: console
---

Scripts for all figures in the paper.
This is Figure 3

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load libraries
```{r}
suppressWarnings(library(GenomicRanges))
suppressWarnings(library(dplyr))
suppressWarnings(library(stringr))
suppressWarnings(library(readr))
suppressWarnings(library(tidyr))
suppressWarnings(library(ggplot2))
suppressWarnings(library(ggplotify))
library(rtracklayer)
library(IRanges)
library(GenomeInfoDb)
library(tidyverse)
library(ggrastr)
library(gridExtra)
library(colorspace)
library(caTools)
library(RColorBrewer)
library(ggpubr)
```


# Figure 3A - Big LAD with d4-5 and i7
```{r}
# data
## pA-DamID, CAST allele from my data
DamID <- as_tibble(import("/DATA/usr/l.dauban/projects/pA-DamID/E1970_ProkDNA/2nd_round/results_mm10_nextseq_strainspecific/tracks/normalized/bin-20kb/WT_F1_LB1_CAS-20kb-combined.bw")) %>% dplyr::rename(DamID = score) %>% filter(seqnames == "chr9") 

## location of clones
clones.df = data.frame(sample = c('donor', 'T162', 'T49', 'T24'),
           x = c(110927601, 112440815, 112520473, 112637307),
           y = rep(-4, 4),
           xend = c(110927601, 112440815, 112520473, 112637307),
           yend = rep(-3.5, 4))

## LAD location from HMM profiles at 20 kb
LAD_loc = data.frame(sample = c('small', 'big', 'other'),
           x = c(109420001, 111560001, 114140001),
           y = rep(2.5, 3),
           xend = c(109760000, 113640000, 114300000),
           yend = rep(2.5, 3))


# Function
PlotDataTracksLight <- function(input_tib, exp_names, color_groups, 
                                centromeres = NULL, plot_chr = "chr1", 
                                plot_start = 1, plot_end = 500e6,
                                smooth = 1, color_list = NULL,
                                fix_yaxis = F, aspect_ratio = NULL,
                                lighten_negative = F, raster = F) {
  
  # Get the scores for the samples
  tib_plot <- input_tib %>%
    dplyr::select(seqnames, start, end, 
                  all_of(exp_names))
  
  if (smooth > 1) {
    tib_plot <- tib_plot %>%
      mutate_at(vars(contains("_")), 
                runmean, k = smooth)
  }
  
  # Filter for plotting window
  tib_plot <- tib_plot %>%
    filter(seqnames == plot_chr,
           start >= plot_start,
           end <= plot_end)
  
  # Gather
  tib_gather <- tib_plot %>%
    gather(key, value, -seqnames, -start, -end) %>%
    mutate(key = factor(key, levels = exp_names),
           fill_column = color_groups[match(key, names(color_groups))],
           fill_column = factor(fill_column, levels = unique(color_groups)))
  
  # If desired, make negative values a lighter shade to improve visualization
  if (lighten_negative) {
    tib_gather <- tib_gather %>%
      mutate(fill_column = interaction(fill_column,
                                       value < 0))
  }
  
  
  
  # Plot
  ylimits <- quantile(tib_gather$value, c(0.001, 0.999), na.rm = T)
  fill_column <- NULL
  
  plt <- tib_gather %>% 
    ggplot(aes(fill = fill_column))
  
  
  # Set all counts tracks to the same limits
  if (raster) {
    plt <- plt + 
      rasterize(geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                              ymin = 0, ymax = value)),
                dpi = 300)
  } else {
    plt <- plt + 
      geom_rect(aes(xmin = start / 1e6, xmax = end / 1e6, 
                    ymin = 0, ymax = value))
  }
  
  plt <- plt + 
    geom_hline(yintercept = 0, size = 0.5) +
    geom_segment(data=clones.df, mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), size =1)+
    geom_segment(data=LAD_loc, mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), size =1, color = "#6BAED6")+
    #geom_rect(aes(xmin = 112440815/1e6, xmax = 112637307/1e6, ymin = -4, ymax = 2), fill = NA, color = "red", alpha = 0.5, inherit.aes = FALSE) +
    facet_grid(key ~ ., scales = "free_y") +
    xlab(paste0(plot_chr, " (Mb)")) +
    ylab("LaminB1/Dam only") +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0.025, 0.025), limits = c(-4, 2.5)) +
    theme_classic() +
    theme(text = element_text(size = 50))
  
  # Centromeres
  if (! is.null(centromeres)) {
    centromeres.plt <- as_tibble(centromeres) %>%
      filter(seqnames == plot_chr) %>%
      gather(key_centromeres, value, start, end)
    
    plt <- plt +
      geom_line(data = centromeres.plt, 
                aes(x = value / 1e6, y = 0),
                color = "black", size = 2)
  }
  
  if (! is.null(color_list)) {
    
    if (lighten_negative) {
      color_list <- c(color_list,
                      lighten(color_list, amount = 0.5))
    }
    
    colors <- levels(tib_gather$fill_column)
    
    color_list <- color_list[1:length(colors)]
    names(color_list) <- colors
    #colors <- recode(colors, !!!color_list)
    
    plt <- plt +
      scale_fill_manual(values = color_list, guide = "none")
  } else {
    plt <- plt +
      scale_fill_brewer(palette = "Set1", guide = "none")
  }
  
  if (fix_yaxis) {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6),
                      ylim = ylimits)
  } else {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6))
  }
  
  if (! is.null(aspect_ratio)) {
    plt <- plt +
      theme(aspect.ratio = aspect_ratio)
  }
  
  plot(plt)
  
}

# Plot
PlotDataTracksLight(input_tib = DamID,
                    exp_names = c("DamID"),
                    color_groups = c(DamID = "pA-DamID"),
                    plot_chr = "chr9", plot_start = 110500000, plot_end = 114700000,
                    color_list = c("#A6CEE3", "#F5C374"),
                    #color_list = brewer.pal(3, "Paired"),
                    aspect_ratio = 1/4,
                    smooth = 5,
                    #fix_yaxis = F,
                    lighten_negative = F,
                    raster = T)

# save
ggsave("Fig3A_LD20231218_locus.pdf", height = 10, width = 30)



```



# Figure 3B - DamID plot
```{r}
# Function
PlotDataTracksLight <- function(input_tib, exp_names, color_groups, 
                                centromeres = NULL, plot_chr = "chr1", 
                                plot_start = 1, plot_end = 500e6,
                                smooth = 1, color_list = NULL,
                                fix_yaxis = F, aspect_ratio = NULL,
                                lighten_negative = F, raster = F) {
  
  # Get the scores for the samples
  tib_plot <- input_tib %>%
    dplyr::select(seqnames, start, end, 
                  all_of(exp_names))
  
  if (smooth > 1) {
    tib_plot <- tib_plot %>%
      mutate_at(vars(contains("Dam")), 
                runmean, k = smooth)
  }
  
  # Filter for plotting window
  tib_plot <- tib_plot %>%
    filter(seqnames == plot_chr,
           start >= plot_start,
           end <= plot_end)
  
  # Gather
  tib_gather <- tib_plot %>%
    gather(key, value, -seqnames, -start, -end) %>%
    mutate(key = factor(key, levels = exp_names),
           fill_column = color_groups[match(key, names(color_groups))],
           fill_column = factor(fill_column, levels = unique(color_groups)),
           color = ifelse(value > 0, "LAD", "iLAD"))
  
  # If desired, make negative values a lighter shade to improve visualization
  # if (lighten_negative) {
  #   tib_gather <- tib_gather %>%
  #     mutate(fill_column = interaction(fill_column,
  #                                      value < 0))
  # }
  
  
  
  # Plot
  ylimits <- quantile(tib_gather$value, c(0.001, 0.999), na.rm = T)
  fill_column <- NULL
  
  plt <- tib_gather %>% 
    ggplot(aes(fill = fill_column))
  
  
  # Set all counts tracks to the same limits
  if (raster) {
    plt <- plt + 
      rasterize(geom_ribbon(aes(x = start/1e6, ymax = ifelse(value<0, value,0), ymin = 0), fill = "#F5C374", alpha = 0.5),
                dpi = 300)
  } else {
    plt <- plt + 
      geom_ribbon(aes(x = start/1e6, ymax = ifelse(value<0, value,0), ymin = 0), fill = "#F5C374", alpha = 0.5)

  }
  
  
  plt <- plt + 
    geom_ribbon(aes(x = start/1e6, ymax = ifelse(value>0, value,0), ymin = 0), fill = "#A6CEE3", alpha = 0.5)+
    geom_line(aes(x = start / 1e6, y = value), size = 0.3)+
    geom_hline(yintercept = 0, size = 0.5) +
    geom_segment(data=clones.df, mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), size =1)+
    geom_segment(data=LAD_loc, mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), size =1, color = "#6BAED6")+
    #geom_rect(aes(xmin = 112440815/1e6, xmax = 112637307/1e6, ymin = -4, ymax = 2), fill = NA, color = "red", alpha = 0.5, inherit.aes = FALSE) +
    facet_grid(key ~ ., scales = "free_y") +
    xlab(paste0(plot_chr, " (Mb)")) +
    ylab("LaminB1/Dam only") +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0.025, 0.025), limits = c(-4, 2.5)) +
    #scale_fill_manual(values = c("#A6CEE3", "#F5C374", "purple"), guide="none") +
    theme_classic() +
    theme(text = element_text(size = 50))
  
  # Centromeres
  if (! is.null(centromeres)) {
    centromeres.plt <- as_tibble(centromeres) %>%
      filter(seqnames == plot_chr) %>%
      gather(key_centromeres, value, start, end)
    
    plt <- plt +
      geom_line(data = centromeres.plt, 
                aes(x = value / 1e6, y = 0),
                color = "black", size = 2)
  }
  
  # if (! is.null(color_list)) {
  #   
  #   if (lighten_negative) {
  #     color_list <- c(color_list,
  #                     lighten(color_list, amount = 0.5))
  #   }
  #   
  #   colors <- levels(tib_gather$fill_column)
  # 
  #   color_list <- color_list[1:length(colors)]
  #   names(color_list) <- colors
  #   #colors <- recode(colors, !!!color_list)
  # 
  #   plt <- plt +
  #     scale_fill_manual(values = color_list, guide = "none")
  # } else {
  #   plt <- plt +
  #     scale_fill_brewer(palette = "Set1", guide = "none")
  # }

  if (fix_yaxis) {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6),
                      ylim = ylimits)
  } else {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6))
  }
  
  if (! is.null(aspect_ratio)) {
    plt <- plt +
      theme(aspect.ratio = aspect_ratio)
  }
  
  plot(plt)
  
}

# Plot
PlotDataTracksLight(input_tib = DamID,
                    exp_names = c("DamID"),
                    color_groups = c(DamID = "pA-DamID"),
                    plot_chr = "chr9", plot_start = 109937608, plot_end = 114946321,
                    color_list = c("#A6CEE3", "#F5C374"),
                    aspect_ratio = 1/3,
                    smooth = 5,
                    #fix_yaxis = F,
                    lighten_negative = F,
                    raster = T)

# save
ggsave("Fig3B_LD20231218_locus.pdf", height = 10, width = 20)


```



# Figure 3C-E - DamID plot
```{r}

clones.df = data.frame(sample = c('donor', 'T51', 'T143', 'strong iLAD', 'weak iLAD' ),
           x = c(110927601, 112653616, 112360112, 114785359, 116258017),
           y = rep(-4, 5),
           xend = c(110927601, 112653616, 112360112, 114785359, 116258017),
           yend = rep(-3.5, 5))


# Function
PlotDataTracksLight <- function(input_tib, exp_names, color_groups, 
                                centromeres = NULL, plot_chr = "chr1", 
                                plot_start = 1, plot_end = 500e6,
                                smooth = 1, color_list = NULL,
                                fix_yaxis = F, aspect_ratio = NULL,
                                lighten_negative = F, raster = F) {
  
  # Get the scores for the samples
  tib_plot <- input_tib %>%
    dplyr::select(seqnames, start, end, 
                  all_of(exp_names))
  
  if (smooth > 1) {
    tib_plot <- tib_plot %>%
      mutate_at(vars(contains("Dam")), 
                runmean, k = smooth)
  }
  
  # Filter for plotting window
  tib_plot <- tib_plot %>%
    filter(seqnames == plot_chr,
           start >= plot_start,
           end <= plot_end)
  
  # Gather
  tib_gather <- tib_plot %>%
    gather(key, value, -seqnames, -start, -end) %>%
    mutate(key = factor(key, levels = exp_names),
           fill_column = color_groups[match(key, names(color_groups))],
           fill_column = factor(fill_column, levels = unique(color_groups)),
           color = ifelse(value > 0, "LAD", "iLAD"))
  
  # If desired, make negative values a lighter shade to improve visualization
  # if (lighten_negative) {
  #   tib_gather <- tib_gather %>%
  #     mutate(fill_column = interaction(fill_column,
  #                                      value < 0))
  # }
  
  
  
  # Plot
  ylimits <- quantile(tib_gather$value, c(0.001, 0.999), na.rm = T)
  fill_column <- NULL
  
  plt <- tib_gather %>% 
    ggplot(aes(fill = fill_column))
  
  
  # Set all counts tracks to the same limits
  if (raster) {
    plt <- plt + 
      rasterize(geom_ribbon(aes(x = start/1e6, ymax = ifelse(value<0, value,0), ymin = 0), fill = "#F5C374", alpha = 0.5),
                dpi = 300)
  } else {
    plt <- plt + 
      geom_ribbon(aes(x = start/1e6, ymax = ifelse(value<0, value,0), ymin = 0), fill = "#F5C374", alpha = 0.5)

  }
  
  
  plt <- plt + 
    geom_ribbon(aes(x = start/1e6, ymax = ifelse(value>0, value,0), ymin = 0), fill = "#A6CEE3", alpha = 0.5)+
    geom_line(aes(x = start / 1e6, y = value), size = 0.3)+
    geom_hline(yintercept = 0, size = 0.5) +
    geom_segment(data=clones.df, mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), size =1)+
    geom_segment(data=LAD_loc, mapping=aes(x=x/1e6, xend=xend/1e6, y=y, yend=yend), size =1, color = "#6BAED6")+
    geom_rect(aes(xmin = 112440815/1e6, xmax = 112637307/1e6, ymin = -4, ymax = 2), fill = NA, color = "red", alpha = 0.5, inherit.aes = FALSE) +
    geom_rect(aes(xmin = 112360112/1e6, xmax = 112154177/1e6, ymin = -4, ymax = 2), fill = NA, color = "blue", alpha = 0.5, inherit.aes = FALSE) +
    #geom_rect(aes(xmin = 112440815/1e6, xmax = 112637307/1e6, ymin = -4, ymax = 2), fill = NA, color = "red", alpha = 0.5, inherit.aes = FALSE) +
    facet_grid(key ~ ., scales = "free_y") +
    xlab(paste0(plot_chr, " (Mb)")) +
    ylab("LaminB1/Dam only") +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0.025, 0.025), limits = c(-4, 2.5)) +
    #scale_fill_manual(values = c("#A6CEE3", "#F5C374", "purple"), guide="none") +
    theme_classic() +
    theme(text = element_text(size = 50))
  
  # Centromeres
  if (! is.null(centromeres)) {
    centromeres.plt <- as_tibble(centromeres) %>%
      filter(seqnames == plot_chr) %>%
      gather(key_centromeres, value, start, end)
    
    plt <- plt +
      geom_line(data = centromeres.plt, 
                aes(x = value / 1e6, y = 0),
                color = "black", size = 2)
  }
  
  # if (! is.null(color_list)) {
  #   
  #   if (lighten_negative) {
  #     color_list <- c(color_list,
  #                     lighten(color_list, amount = 0.5))
  #   }
  #   
  #   colors <- levels(tib_gather$fill_column)
  # 
  #   color_list <- color_list[1:length(colors)]
  #   names(color_list) <- colors
  #   #colors <- recode(colors, !!!color_list)
  # 
  #   plt <- plt +
  #     scale_fill_manual(values = color_list, guide = "none")
  # } else {
  #   plt <- plt +
  #     scale_fill_brewer(palette = "Set1", guide = "none")
  # }

  if (fix_yaxis) {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6),
                      ylim = ylimits)
  } else {
    plt <- plt + 
      coord_cartesian(xlim = c(max(c(plot_start,
                                     min(tib_gather$start))) / 1e6,
                               min(c(plot_end,
                                     max(tib_gather$end))) / 1e6))
  }
  
  if (! is.null(aspect_ratio)) {
    plt <- plt +
      theme(aspect.ratio = aspect_ratio)
  }
  
  plot(plt)
  
}

# Plot
PlotDataTracksLight(input_tib = DamID,
                    exp_names = c("DamID"),
                    color_groups = c(DamID = "pA-DamID"),
                    plot_chr = "chr9", plot_start = 109937608, plot_end = 119448158,
                    color_list = c("#A6CEE3", "#F5C374"),
                    aspect_ratio = 1/3,
                    smooth = 5,
                    #fix_yaxis = F,
                    lighten_negative = F,
                    raster = T)

# save
ggsave("Fig3CE_LD20231218_locus.pdf", height = 10, width = 30)


```

