---
title: "Fig_Supp_1_LD20230606_Fzd5_Nanog"
date: "2023-06-06"
output: 
  html_document:
    theme: journal #cerulean
    highlight: monochrome
    toc: true
    toc_float: true
    code_folding: show
  editor_options:
    chunk_output_type: console
---

Scripts for all figures in the paper.
This is Figure Supp 1

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
suppressWarnings(library(GenomicRanges))
suppressWarnings(library(dplyr))
suppressWarnings(library(stringr))
suppressWarnings(library(readr))
suppressWarnings(library(tidyr))
suppressWarnings(library(ggplot2))
suppressWarnings(library(ggplotify))
library(rtracklayer)
library(IRanges)
library(GenomeInfoDb)
library(tidyverse)
library(ggrastr)
library(gridExtra)
library(colorspace)
library(caTools)
library(RColorBrewer)
```


# Figure S1A - SB hopping behaviour in Fzd5 iLAD
```{r}

# Load metadata of integrations
metadata <- dplyr::tibble(file = dir("/DATA/usr/l.dauban/projects/TagMap/E1682_SB_hopped_clones/Output/mm10/home/insertions/", recursive = T, full.names = T)) %>%
  dplyr::filter(grepl("insertions", file)) %>%
  dplyr::mutate(sample = stringr::str_remove(basename(file), "\\..*"))


# Load all mapped insertion sites into single tibble
tib <- dplyr::bind_rows(lapply(
  1:nrow(metadata),
  function(i) {
    tmp <- readr::read_tsv(metadata$file[i],
      col_types = cols(
        seqnames = col_character(),
        start = col_double(),
        end = col_double(),
        start_gap = col_double(),
        end_gap = col_double(),
        gap_concordance = col_double(),
        count = col_double(),
        D = col_double(),
        p = col_double(),
        concordance = col_double(),
        p_adj = col_double(),
        strand = col_character(),
        name = col_character(),
      )
    ) %>%
      dplyr::mutate(sample = metadata$sample[i])
  }
))

# Convert 'seqnames' to factor
chromosomes <- paste0("chr", c(1:19, "X"))
tib <- tib %>%
  dplyr::mutate(seqnames = factor(seqnames, levels = chromosomes)) %>%
  tidyr::drop_na(seqnames)

# Add factor 'hopped' describing source of hopping
tib <- tib %>%
  dplyr::mutate(sample = factor(sample, )) %>%
  dplyr::mutate(
    hopped = case_when(
      grepl("Fzd5", sample) ~ "Fzd5",
      grepl("Tdgf1", sample) ~ "Tdgf1",
      grepl("Nanog", sample) ~ "Nanog",
      T ~ "unknown"
    ),
    hopped = factor(hopped, c("Fzd5", "Tdgf1", "Nanog"))
  ) %>%
  # Add factor 'library' describing samples originating from pool or clone libraries
  dplyr::mutate(
    library = case_when(
      grepl("_D", sample) ~ "pool",
      grepl("_cl", sample) ~ "clone",
      grepl("_FACS", sample) ~ "pool",
      T ~ "unknown"
    ),
    library = factor(library, c("pool", "clone"))
  )

# data
donor <- GenomicRanges::GRanges(seqnames = "chr1", ranges = IRanges(start = 64986916, end = 64994318), strand = "*")

LAD_left <- data.frame(xmin=60880001/1e6, xmax=62660000/1e6, ymin=-Inf, ymax=Inf)
LAD_right <- data.frame(xmin=65280001/1e6, xmax=66700000/1e6, ymin=-Inf, ymax=Inf)

# Color-blind colors
BLUE <- '#56B4E9'
YELLOW <- '#F0E442'
RED <- '#D55E00'

# process
Fzd5.data <- tib %>%
  filter(hopped == 'Fzd5')
Fzd5.distinct <- Fzd5.data %>%
  select(seqnames, start, end, strand) %>%
  distinct()
Fzd5.gr <- makeGRangesFromDataFrame(Fzd5.distinct, keep.extra.columns = T)
Fzd5.distance <- as_tibble(distanceToNearest(Fzd5.gr, donor, ignore.strand = T)) %>%
  mutate(
    location = start(Fzd5.gr[queryHits]),
    upstream = location < start(donor),
    distance = ifelse(upstream == T, -distance, distance)
  )

# plot
ggplot(Fzd5.distance, aes(x = location/1e6)) +
  geom_rect(data = LAD_left, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), fill = "#A6CEE3", alpha = 0.5, inherit.aes = FALSE) +
  geom_rect(data = LAD_right, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), fill = "#A6CEE3", alpha = 0.5, inherit.aes = FALSE) +
  geom_histogram(fill = "gray85", color = "gray80",  binwidth = 0.1, alpha = 0.5)+
  geom_density(aes(y=..scaled..*95), n = 4096, size = 1) +
  scale_y_continuous(sec.axis = sec_axis(~./95, name = "Integration density", breaks = seq(0,1,0.2)))+
  geom_rug(length = unit(0.08, "npc")) +
  coord_cartesian(xlim = c(62.2, 66.7), ylim = c(0, 100), expand = FALSE) +
  theme_bw() +
  geom_vline(aes(xintercept = start(donor) / 1e6), col = RED, size = 1) +
  geom_vline(aes(xintercept = LAD_left$xmin), col = BLUE, size = 1) +
  geom_vline(aes(xintercept = LAD_left$xmax), col = BLUE, size = 1) +
  geom_vline(aes(xintercept = LAD_right$xmin), col = BLUE, size = 1) +
  geom_vline(aes(xintercept = LAD_right$xmax), col = BLUE, size = 1) +
  labs(title = 'Fzd5', x = "chr1 (Mb)", y = 'Integration counts') +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size = 50)) 

# save
ggsave("FigS1A_LD20230919_Fzd5.pdf", height = 10, width = 20)

# number of integration
# total
nrow(Fzd5.distance)

# in the plotted window
Fzd5.distance %>% filter(location > 62.2e6 & location < 66.7e6) %>% nrow()

# number of integrations in iLAD
damid <- import("/DATA/usr/l.dauban/projects/pA-DamID/E1970_ProkDNA/2nd_round/results_mm10_nextseq_strainspecific/tracks/normalized/bin-20kb/WT_F1_LB1_CAS-20kb-combined.bw")

Fzd5_ovl_integ <- findOverlaps(Fzd5.gr, damid, select = "arbitrary")
Fzd5.gr$damid <- damid$score[Fzd5_ovl_integ]
Fzd5.gr$LAD = ifelse(Fzd5.gr$damid>0, "LAD", "iLAD")

Fzd5.gr %>% data.frame() %>% filter(seqnames == "chr1") %>% filter(LAD == "iLAD")

```




# Figure S1B - SB hopping behaviour in Nanog iLAD
```{r}

# Load metadata of integrations
metadata <- dplyr::tibble(file = dir("/DATA/usr/l.dauban/projects/TagMap/E1682_SB_hopped_clones/Output/mm10/home/insertions/", recursive = T, full.names = T)) %>%
  dplyr::filter(grepl("insertions", file)) %>%
  dplyr::mutate(sample = stringr::str_remove(basename(file), "\\..*"))


# Load all mapped insertion sites into single tibble
tib <- dplyr::bind_rows(lapply(
  1:nrow(metadata),
  function(i) {
    tmp <- readr::read_tsv(metadata$file[i],
      col_types = cols(
        seqnames = col_character(),
        start = col_double(),
        end = col_double(),
        start_gap = col_double(),
        end_gap = col_double(),
        gap_concordance = col_double(),
        count = col_double(),
        D = col_double(),
        p = col_double(),
        concordance = col_double(),
        p_adj = col_double(),
        strand = col_character(),
        name = col_character(),
      )
    ) %>%
      dplyr::mutate(sample = metadata$sample[i])
  }
))

# Convert 'seqnames' to factor
chromosomes <- paste0("chr", c(1:19, "X"))
tib <- tib %>%
  dplyr::mutate(seqnames = factor(seqnames, levels = chromosomes)) %>%
  tidyr::drop_na(seqnames)

# Add factor 'hopped' describing source of hopping
tib <- tib %>%
  dplyr::mutate(sample = factor(sample, )) %>%
  dplyr::mutate(
    hopped = case_when(
      grepl("Fzd5", sample) ~ "Fzd5",
      grepl("Tdgf1", sample) ~ "Tdgf1",
      grepl("Nanog", sample) ~ "Nanog",
      T ~ "unknown"
    ),
    hopped = factor(hopped, c("Fzd5", "Tdgf1", "Nanog"))
  ) %>%
  # Add factor 'library' describing samples originating from pool or clone libraries
  dplyr::mutate(
    library = case_when(
      grepl("_D", sample) ~ "pool",
      grepl("_cl", sample) ~ "clone",
      grepl("_FACS", sample) ~ "pool",
      T ~ "unknown"
    ),
    library = factor(library, c("pool", "clone"))
  )

# data
donor <- GenomicRanges::GRanges(seqnames = "chr6", ranges = IRanges(start = 122650131, end = 122650131), strand = "*")

LAD_left_2 <- data.frame(xmin=121340001/1e6, xmax=121440000/1e6, ymin=-Inf, ymax=Inf)
LAD_left <- data.frame(xmin=121580001/1e6, xmax=122280000/1e6, ymin=-Inf, ymax=Inf)
LAD_right <- data.frame(xmin=122880001/1e6, xmax=124380000/1e6, ymin=-Inf, ymax=Inf)

# Color-blind colors
BLUE <- '#56B4E9'
YELLOW <- '#F0E442'
RED <- '#D55E00'

# process
Nanog.data <- tib %>%
  filter(hopped == 'Nanog')
Nanog.distinct <- Nanog.data %>%
  select(seqnames, start, end, strand) %>%
  distinct()
Nanog.gr <- makeGRangesFromDataFrame(Nanog.distinct, keep.extra.columns = T)
Nanog.distance <- as_tibble(distanceToNearest(Nanog.gr, donor, ignore.strand = T)) %>%
  mutate(
    location = start(Nanog.gr[queryHits]),
    upstream = location < start(donor),
    distance = ifelse(upstream == T, -distance, distance)
  )

# plot
ggplot(Nanog.distance, aes(x = location/1e6)) +
  geom_rect(data = LAD_left, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), fill = "#A6CEE3", alpha = 0.5, inherit.aes = FALSE) +
  geom_rect(data = LAD_left_2, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), fill = "#A6CEE3", alpha = 0.5, inherit.aes = FALSE) +
  geom_rect(data = LAD_right, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), fill = "#A6CEE3", alpha = 0.5, inherit.aes = FALSE) +
  geom_histogram(fill = "gray85", color = "gray80",  binwidth = 0.1, alpha = 0.5)+
  geom_density(aes(y=..scaled..*69), n = 4096, size = 1) +
  scale_y_continuous(sec.axis = sec_axis(~./69, name = "Integration density", breaks = seq(0,1,0.2)))+
  geom_rug(length = unit(0.08, "npc")) +
  coord_cartesian(xlim = c(120.5, 125), ylim = c(0, 73), expand = FALSE) +
  theme_bw() +
  geom_vline(aes(xintercept = start(donor) / 1e6), col = RED, size = 1) +
  geom_vline(aes(xintercept = LAD_left$xmin), col = BLUE, size = 1) +
  geom_vline(aes(xintercept = LAD_left$xmax), col = BLUE, size = 1) +
  geom_vline(aes(xintercept = LAD_left_2$xmin), col = BLUE, size = 1) +
  geom_vline(aes(xintercept = LAD_left_2$xmax), col = BLUE, size = 1) +
  geom_vline(aes(xintercept = LAD_right$xmin), col = BLUE, size = 1) +
  geom_vline(aes(xintercept = LAD_right$xmax), col = BLUE, size = 1) +

  labs(title = 'Nanog', x = "chr6 (Mb)", y = 'Integration counts') +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size = 50))


# save
ggsave("FigS1B_LD20230919_Nanog.pdf", height = 10, width = 20)

# number of integration
# total
nrow(Nanog.distance)

# in the plotted window
Nanog.distance %>% filter(location > 120.5e6 & location < 125e6) %>% nrow()


# number of integrations in iLAD
Nanog_ovl_integ <- findOverlaps(Nanog.gr, damid, select = "arbitrary")
Nanog.gr$damid <- damid$score[Nanog_ovl_integ]
Nanog.gr$LAD = ifelse(Nanog.gr$damid>0, "LAD", "iLAD")

Nanog.gr %>% data.frame() %>% filter(seqnames == "chr6") %>% filter(LAD == "iLAD")


```
